apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-microservicio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-microservicio
  template:
    metadata:
      labels:
        app: ms-microservicio
    spec:
      containers:
      - name: ms-microservicio
        image: cmendoza83/ms-microservicio:latest
        ports:
        - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: service-ms-microservicio
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: ms-microservicio
