name: CICD_EjercicioFinal
on:
  push:
    branches: 
    - feature-ms-carlosMendoza-ejercicioFinal
  ##workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonacion de codigo
        uses: actions/checkout@v4
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Compilacion
        run: |
          #mvn package
          mvn -B clean verify -Pcoverage
        
      - name: Ejecucion Test Unitarios
        run: |
          mvn package test
        
      - name: Reporte Jacoco
        run: |
          mvn jacoco:report
              
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{secrets.SONAR_TOKEN}} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=cmendo \
          -Dsonar.projectKey=cmendo_microservicio-java
      
      #- name: SonarQube Quality Gate Check
       # uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        #with:
             scanMetadataReportFile: target/sonar/report-task.txt
