name: CICD_EjercicioFinal

on:
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'

      #- name: Setup Java JDK
       # uses: actions/setup-java@v4.2.1
        #with:
         # java-version: '8'
          #distribution: 'temurin'
      
      - name: Compilacion
        run: mvn package

      - name: Ejecucion Test Unitarios
        run: mvn package test

      - name: Reporte Jacoco
        run: mvn jacoco:report

      #- name: Cobertura de Test
       # run: |
        #    cat target/site/jacoco/index.html | grep "Overall coverage" | awk -F'>' '{print $3}' | awk -F'80%' '{print $1}'

      - name: Analisis SonarCloud
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.token=${{secrets.SONAR_TOKEN}} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=cmendo \
            -Dsonar.projectKey=cmendo_microservicio-java
